name: ecstatic_chiahui
services:
  veapp:
    cpu_shares: 90
    command: []
    container_name: veapp
    deploy:
      resources:
        limits:
          memory: 2048M
    hostname: veapp
    image: tekihodon/vesimple:1.7.11
    dns:
      - 8.8.8.8
      - 8.8.4.4
    labels:
      icon: https://icon.casaos.io/main/all/veapp.png
    ports:
      - target: 3333
        published: "3333"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/veapp/app/config.json
        target: /app/config.json
      - type: bind
        source: /tmp/casaos-compose-app-432994938/static/qr
        target: /app/static/qr
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: 8keyslive.store
  icon: https://icon.casaos.io/main/all/veapp.png
  index: /
  is_uncontrolled: false
  port_map: "443"
  scheme: https
  store_app_id: ecstatic_chiahui
  title:
    custom: ""
    en_us: veapp
